// Fetch Groups
export const FETCH_GROUPS_BEGIN = 'FETCH_GROUPS_BEGIN';
export const FETCH_GROUPS_SUCCESS = 'FETCH_GROUPS_SUCCESS';
export const FETCH_GROUPS_FAILURE = 'FETCH_GROUPS_FAILURE';

// New Group
  // Saving
export const SAVE_GROUP_BEGIN = 'SAVE_GROUP_BEGIN';
export const SAVE_GROUP_SUCCESS = 'SAVE_GROUP_SUCCESS';
export const SAVE_GROUP_FAILURE = 'SAVE_GROUP_FAILURE';
  // Updating New Group
export const UPDATE_NAME = 'UPDATE_NAME';
export const UPDATE_ROTATEES = 'UPDATE_ROTATEES';
export const UPDATE_NEW_ROTATEE_NAME = 'UPDATE_NEW_ROTATEE_NAME';


// Select Group
export const SELECT_GROUP = 'SELECT_GROUP';

//Edit Group
export const EDIT_GROUP_BEGIN = 'EDIT_GROUP_BEGIN';
export const EDIT_GROUP_SUCCESS = 'EDIT_GROUP_SUCCESS';
export const EDIT_GROUP_FAILURE = 'EDIT_GROUP_FAILURE';