// Fetch Groups
export const FETCH_GROUPS_BEGIN = 'FETCH_GROUPS_BEGIN';
export const FETCH_GROUPS_SUCCESS = 'FETCH_GROUPS_SUCCESS';
export const FETCH_GROUPS_FAILURE = 'FETCH_GROUPS_FAILURE';

// New Group
  // Saving
  export const SAVE_NEW_GROUP_BEGIN = 'SAVE_NEW_GROUP_BEGIN';
  export const SAVE_NEW_GROUP_SUCCESS = 'SAVE_NEW_GROUP_SUCCESS';
  export const SAVE_NEW_GROUP_FAILURE = 'SAVE_NEW_GROUP_FAILURE';
  // Updating New Group
  export const UPDATE_NEW_NAME = 'UPDATE_NEW_NAME';
  export const UPDATE_NEW_ROTATEES = 'UPDATE_NEW_ROTATEES';
  export const UPDATE_NEW_ROTATEE_NAME = 'UPDATE_NEW_ROTATEE_NAME';
  // Clear New Group
  export const CLEAR_NEW_ROTATEE_NAME = 'CLEAR_NEW_ROTATEE_NAME';
  export const CLEAR_NEW_GROUP = 'CLEAR_NEW_GROUP';

// ACTIVE GROUP
  // Select Group
  export const SELECT_GROUP = 'SELECT_GROUP';
  // Edit Group
  export const EDIT_GROUP_BEGIN = 'EDIT_GROUP_BEGIN';
  export const EDIT_GROUP_SUCCESS = 'EDIT_GROUP_SUCCESS';
  export const EDIT_GROUP_FAILURE = 'EDIT_GROUP_FAILURE';
  // Update Active Group
  export const UPDATE_ACTIVE_NAME = 'UPDATE_ACTIVE_NAME';
  export const UPDATE_ACTIVE_ROTATEES = 'UPDATE_ACTIVE_ROTATEES';
  export const UPDATE_ACTIVE_QUEUE = 'UPDATE_ACTIVE_QUEUE';
  export const UPDATE_ACTIVE_HISTORY = 'UPDATE_ACTIVE_HISTORY';
  export const UPDATE_ACTIVE_ID = 'UPDATE_ACTIVE_ID';
  export const UPDATE_ACTIVE_VERSION = 'UPDATE_ACTIVE_VERSION';
  export const UPDATE_ACTIVE_ROTATEE_NAME = 'UPDATE_ACTIVE_ROTATEE_NAME';
  export const ADD_ACTIVE_ROTATEE = 'ADD_ACTIVE_ROTATEE';
  // Clear Active Group
  export const CLEAR_ACTIVE_ROTATEE_NAME = 'CLEAR_ACTIVE_ROTATEE_NAME';
  export const CLEAR_ACTIVE_GROUP = 'CLEAR_ACTIVE_GROUP';

  // Update Active Group Request
  export const UPDATE_ACTIVE_GROUP_BEGIN = 'UPDATE_ACTIVE_GROUP_BEGIN';
  export const UPDATE_ACTIVE_GROUP_SUCCESS = 'UPDATE_ACTIVE_GROUP_SUCCESS';
  export const UPDATE_ACTIVE_GROUP_FAILURE = 'UPDATE_ACTIVE_GROUP_FAILURE';